config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  root to: 'home#home'

  namespace :admin do
    resources :users
    resources :posts
    resources :categories
  end

  namespace :user do
    resources :nft_posts do
      collection do
        get :explore
        get :mobile_nft
      end
    end
    resources :offers do
      collection do
        get :explore
      end
    end
    resources :bids
    resources :users, only: [:edit, :update]
    get :profile, to: 'users#show'
  end
  resources :users, only: [:update]
  resources :nfts, only: [:show]

  get "/home/*page" => "home#show"

  # API routes
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_for :users,
                  controllers: {
                    sessions: 'api/v1/sessions',
                    registrations: 'api/v1/registrations',
                    passwords: 'api/v1/passwords'
                  },
                  path_names: {
                    sign_in: :login,
                    sign_out: :logout,
                    registration: :signup,
                    password: :forgot_password
                  }

      devise_scope :user do
        post 'users/verify_otp', to: 'registrations#verify_otp'
        post 'users/send_otp', to: 'registrations#send_otp'
        post 'users/resend_otp', to: 'registrations#resend_otp'
      end

      resources :users, only: [:show, :update] do
        member do
          get :profile, to: 'users#show'
          patch :update_profile, to: 'users#update'
          post :follow
          post :unfollow
          get :followers
          get :following
          get :details
          get :posts
        end
      end

      resources :posts do
        collection do
          post :delete
        end
        resources :comments
      end
      resources :roles, only: :index
      resources :feeds, only: :index
      resources :nft_posts, only: [:index, :show]
      resources :nfts, only: [] do
        collection do
          post :sign_nft
          post :sign_royalty
        end
      end
      resources :likes, only: [] do
        collection do
          post :like
          post :dislike
        end
      end
    end
  end
end

app/views/shared/_navigations.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %a.navbar-brand{href: '/'} Talent
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %form.form-inline.my-2.my-lg-0
      - if user_signed_in?
        = render partial: 'shared/users_navigations'
        %span.navbar-toggler-icon
        = link_to 'Logout', destroy_user_session_path, method: :delete, data: { turbo_method: :delete }
      - else
        = link_to 'Login', new_user_session_path

app/views/shared/_notices.html.haml
- flash.each do |msg_type, message|
  .alert
    .container
      %button.close{"data-dismiss" => "alert"}
        %span ×
      = message

app/views/shared/_users_navigations.html.haml
%ul.navbar-nav.mr-auto
  %li.nav-item.active
    %a.nav-link{href: '/'}
      Home
      %span.sr-only (current)
  %li.nav-item.dropdown
    %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
      Profile
    .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
      = link_to 'Users', users_path, class: 'dropdown-item'
    .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
      = link_to 'Categories', categories_path, class: 'dropdown-item'
    .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
      = link_to 'Posts', posts_path, class: 'dropdown-item'