config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  root to: 'home#home'

  namespace :admin do
    resources :users
    resources :posts
    resources :categories
  end

  namespace :user do
    resources :nft_posts do
      collection do
        get :explore
        get :mobile_nft
      end
    end
    resources :offers do
      collection do
        get :explore
      end
    end
    resources :bids
    resources :users, only: [:edit, :update]
    get :profile, to: 'users#show'
  end
  resources :users, only: [:update]
  resources :nfts, only: [:show]

  get "/home/*page" => "home#show"

  # API routes
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_for :users,
                  controllers: {
                    sessions: 'api/v1/sessions',
                    registrations: 'api/v1/registrations',
                    passwords: 'api/v1/passwords'
                  },
                  path_names: {
                    sign_in: :login,
                    sign_out: :logout,
                    registration: :signup,
                    password: :forgot_password
                  }

      devise_scope :user do
        post 'users/verify_otp', to: 'registrations#verify_otp'
        post 'users/send_otp', to: 'registrations#send_otp'
        post 'users/resend_otp', to: 'registrations#resend_otp'
      end

      resources :users, only: [:show, :update] do
        member do
          get :profile, to: 'users#show'
          patch :update_profile, to: 'users#update'
          post :follow
          post :unfollow
          get :followers
          get :following
          get :details
          get :posts
        end
      end

      resources :posts do
        collection do
          post :delete
        end
        resources :comments
      end
      resources :roles, only: :index
      resources :feeds, only: :index
      resources :nft_posts, only: [:index, :show]
      resources :nfts, only: [] do
        collection do
          post :sign_nft
          post :sign_royalty
        end
      end
      resources :likes, only: [] do
        collection do
          post :like
          post :dislike
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, uniqueness: { case_sensitive: true }

  belongs_to :role, optional: true

  has_many :posts, dependent: :destroy
  has_many :nft_posts, dependent: :destroy
  has_many :offers, dependent: :destroy
  has_many :bids, dependent: :destroy

  # to whom I am following
  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  has_many :followees, through: :followed_users

  # users who are following me
  has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
  has_many :followers, through: :following_users
  has_many :likes, dependent: :destroy
  has_many :cliamed_posts, foreign_key: :claimer_id, class_name: 'NftPost'

  def generate_otp
    # rand.to_s[2..7]
    "000000"
  end

  def generate_user_otp!
    self.mobile_otp = generate_otp
    self.otp_sent_at = Time.now.utc

    unless persisted?
      self.email = "#{mobile}@demo.com"
    end

    save(validate: false)
  end

  def otp_valid?
    # (self.otp_sent_at + 5.minutes) > Time.now.utc
    true
  end

  def generate_jwt
    JWT.encode(
      { id: id, exp: 90.days.from_now.to_i },
      Rails.application.secrets.secret_key_base
    )
  end

  def name
    "#{first_name} #{last_name}"
  end

  def listing_offers
    Offer.joins(:nft_post).where(nft_posts: { user_id: id })
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'

  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
    @posts = @user.posts.includes(comments: :replies)
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      format.js
      format.json {
        if @user.update(user_params)
          render json: @user
        else
          render json: @user.errors.first, status: :unprocessable_entity
        end
      }
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :username,
      :first_name,
      :last_name,
      :daily_news,
      :nft_account,
      :wallet_address,
      :nft_details
    )
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApiController

      def show;end

      def update
        upload_and_set_attr(:blr_image, params[:user][:blr_image], 'blur-image')
        upload_and_set_attr(:image_url, params[:user][:image], 'profile-image')
        upload_and_set_attr(:video_url, params[:user][:video], 'profile-video')

        if current_user.update(user_params)
          render json: {
            messages: 'User updated successfully',
            is_success: true,
            data: { user: current_user }
          }, status: :ok
        else
          render json: {
            messages: current_user.errors.full_messages.first,
            is_success: false,
            data: {}
          }, status: :unprocessable_entity
        end
      end

      def follow
        @user = User.find(params[:id])

        if !current_user.followees.include?(@user)
          current_user.followees << @user
          render json: {
            messages: 'You have followed user successfully',
            is_success: true,
            data: {}
          }, status: :ok
        else
          render json: {
            messages: current_user.errors.full_messages.first || 'User already Followed',
            is_success: false,
            data: {}
          }, status: :unprocessable_entity
        end
      end

      def unfollow
        @user = User.find(params[:id])
        followed_user = current_user.followed_users.find_by(followee_id: @user.id)

        if followed_user && followed_user.destroy
          render json: {
            messages: 'Successfully unfollowed a user',
            is_success: true,
            data: {}
          }, status: :ok
        else
          render json: {
            messages: followed_user.present? ? current_user.errors.full_messages.first : 'You are not following to User',
            is_success: false,
            data: {}
          }, status: :unprocessable_entity
        end
      end

      def followers
        @user = User.find_by(id: params[:id])
        if @user
          @followers = @user.followers
        else
          render json: {
            messages: 'User not found',
            is_success: false,
            data: {}
          }, status: :unprocessable_entity
        end
      end

      def following
        @user = User.find_by(id: params[:id])
        if @user
          @followings = @user.followees
        else
          render json: {
            messages: 'User not found',
            is_success: false,
            data: {}
          }, status: :unprocessable_entity
        end
      end

      def details
        @user = User.find_by(id: params[:id])
        unless @user
          render json: {
            messages: 'User not found',
            is_success: false,
            data: {}
          }, status: :unprocessable_entity
        end
      end

      def posts
        @user = User.find_by(id: params[:id])
        if @user
          @is_following = current_user.followees.include?(@user)
          @posts = @user.posts.except_deleted
                    .page(params[:page]).order(created_at: :desc).per_page(10) if @is_following
        else
          render json: {
            messages: 'User not found',
            is_success: false,
            data: {}
          }, status: :unprocessable_entity
        end
      end

      private

      def user_params
        params.require(:user).permit(
          :first_name,
          :last_name,
          :daily_news,
          :image_url,
          :video_url,
          :wallet_address,
          :role_id
        )
      end

      def upload_and_set_attr(attribute, file, attr_type)
        if file
          extension = File.extname(file)
          folder_path = "#{Rails.env}/#{current_user.id}/profiles/#{current_user.id}-#{Time.now.to_i}-#{attr_type}#{extension}"
          upload_object = upload_to_s3(file, folder_path)
          current_user.send("#{attribute}=", upload_object.public_url) if upload_object
        end
      end
    end
  end
end

app/controllers/user/bids_controller.rb
class User::BidsController < ApplicationController
  layout 'user'

  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!

  def new
    @offer = Offer.find(params[:offer_id])
    @bid = current_user.bids.new(offer: @offer)
    @highest_bid_amount = @offer.bids.maximum(:amount) || 0

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @offer = current_user.bids.new(offer_params)
    respond_to do |format|
      if @offer.save
        format.html { redirect_to user_offer_url(@bid.offer_id), notice: "Bid was successfully created." }
        format.json { render json: @bid, status: :created }
        format.js   { render :new, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
        format.turbo_stream { render :form_update, status: :unprocessable_entity }
      end
    end
  end

  private
    def offer_params
      params.require(:bid).permit(
        :amount,
        :details,
        :offer_id
      )
    end
end

app/controllers/user/nft_posts_controller.rb
class User::NftPostsController < ApplicationController
  layout 'user'

  include UploadToS3

  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!

  def new
    @nft_post = current_user.nft_posts.new
    @royalty_nominator = @nft_post.royalty_nominators.build
  end

  def create
    @nft_post = current_user.nft_posts.new(nft_post_params.except(:attachment))

    respond_to do |format|
      if @nft_post.save
        upload_and_set_attr(nft_post_params.dig(:attachment))

        @offer = @nft_post.offers.last
        redirect_url = @offer.present? ? user_offer_url(@offer) : user_nft_post_url(@nft_post)

        format.html { redirect_to redirect_url, notice: "Post was successfully created." }
        format.json { render json: @nft_post, status: :created }
        format.js   { render :new, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.js { render json: @nft_post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @nft_post = NftPost.find(params[:id])

    respond_to do |format|
      if @nft_post.update(nft_post_params)
        format.js
        format.json { render json: @nft_post, status: :ok }
      else
        format.json {
          render json: @nft_post.errors.first, status: :unprocessable_entity
        }
      end
    end
  end

  def explore
    @nft_posts = NftPost.state_created.includes(:user, :likes)
  end

  def show
    @nft_post = NftPost.find_by(id: params[:id])
    @author = @nft_post.user
    @nft_id = SignNftRequest.last.count
    @offers = @nft_post.offers
    @can_claim_offer = DateTime.now > @nft_post.end_date
    @highest_offer_id = @offers.order('amount DESC').first.id if @offers.any?
  end

  def mobile_nft;end

  private
    def nft_post_params
      params.require(:nft_post).permit(
        :title,
        :description,
        :category,
        :hashtags,
        :offer_amount,
        :max_supply,
        :attachment,
        :attachment_url,
        :details,
        :start_price,
        :target_price,
        :end_date,
        :nft_id,
        :state,
        :nft_token_id,
        :shared_royalty,
        :claimer_id,
        :claimer_wallet_address,
        royalty_nominators_attributes: [
          :id,
          :payee_address,
          :shares,
          :_destroy,
        ],
      )
    end

    def upload_and_set_attr(file)
      if file
        extension = File.extname(file)

        folder_path = "#{Rails.env}/#{current_user.id}/nft_posts/#{@nft_post.id}/#{Time.now.to_i}-#{file.original_filename}"
        upload_object = upload_to_s3(file, folder_path)
        @nft_post.update(
          attachment_url: upload_object.public_url,
          content_type: file.content_type,
          extension: extension
        ) if upload_object
      end
    end
end

app/controllers/user/offers_controller.rb
class User::OffersController < ApplicationController
  layout 'user'

  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!

  def new
    @nft_post = NftPost.find(params[:nft_post_id])
    @offer = current_user.offers.new
    @highest_offer_amount = @nft_post.offers.maximum(:amount) || 0

    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @offer = current_user.offers.new(offer_params)
    respond_to do |format|
      if @offer.save
        format.html { redirect_to user_nft_post_url(@offer.nft_post_id), notice: "Offer was successfully created." }
        format.json { render json: @offer, status: :created }
        format.js   { render :new, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
        format.turbo_stream { render :form_update, status: :unprocessable_entity }
      end
    end
  end

  def explore
    @offers = Offer.state_created.includes(:user, :likes)
  end

  def show
    @offer = Offer.find_by(id: params[:id])
    @author = @offer.user
    @nft_id = SignNftRequest.last.count
    @bids = @offer.bids
    @can_claim_bid = DateTime.now > @offer.end_date
    @highest_bid_id = @bids.order('amount DESC').first.id if @bids.any?
  end

  private
    def offer_params
      params.require(:offer).permit(
        :amount,
        :details,
        :nft_post_id
      )
    end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  layout 'user'

  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!

  def show
    if params[:page] == 'listings'
      @listing_offers = current_user.listing_offers
    elsif params[:page] == 'created'
      @nft_posts = current_user.nft_posts.state_created
    else
      @nft_posts = current_user.cliamed_posts
    end
  end

  def update
    respond_to do |format|
      if current_user.update(user_params)
        format.html { redirect_to user_user_path(current_user), notice: "Details was successfully updated." }
        format.json { render json: current_user, status: :created }
        format.js   { render :show, status: :created }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: current_user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def user_params
      params.require(:user).permit(
        :amount,
        :details,
        :nft_post_id
      )
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      format.js
      format.json {
        if @user.update(user_params)
          render json: @user
        else
          render json: @user.errors.first, status: :unprocessable_entity
        end
      }
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :username,
      :first_name,
      :last_name,
      :daily_news,
      :nft_account,
      :wallet_address,
      :nft_details
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def profile_url(user)
    user.image_url || '/user/img/default/img-1.png'
  end

  def can_claim_offer?(nft_post, offer_id)
    offers = nft_post.offers
    is_offer_expired = DateTime.now > nft_post.end_date
    highest_offer_id = offers.order('amount DESC').first.id if offers.any?

    is_offer_expired && (highest_offer_id == offer_id)
  end
end

app/views/user/users/_collected_offers.html.haml
- @nft_posts.each do |nft_post|
  .SL_Outer_Box
    .SL_Box
      = link_to user_nft_post_url(nft_post) do
        .img-box
          %img{src: "#{nft_post.attachment_url}"}/
      .text-box.w-100.d-flex.justify-content-between
        .text-box-left.d-flex.flex-column.justify-content-center.align-items-center.align-items-lg-start
          %span.name-1
            = nft_post.title
          %strong.name-2
            = nft_post.category
          %strong.name-3
            = "##{nft_post.nft_offer_id}"
        .text-box-right.d-flex.flex-column.justify-content-end.align-items-end
          %span.name-4
            = nft_post.offer_amount
          %span.name-5.d-flex.align-items-center
            = nft_post.likes.count
            %img.like-icon{src: "/user/img/default/like.png"}/

app/views/user/users/_listing_offers.html.haml
%table.table
  %thead
    %tr
      %th{scope: "col"} User
      %th{scope: "col"} NFT Post ID
      %th{scope: "col"} NFT Post Title
      %th{scope: "col"} Offer Amount
      %th{scope: "col"} Actions
  %tbody
    - @listing_offers.each do |offer|
      %tr
        %th{scope: "row"}
          = offer.user.name.presence || "User #{offer.user.id}"
        %td
          = offer.nft_post.id
        %td
          = offer.nft_post.title
        %td
          = offer.amount
        %td
          - if can_claim_offer?(offer.nft_post, offer.id)
            = link_to 'Claim Offer', 'javascript:void(0)', class: 'btn btn-primary', id: 'claimOffer'

app/views/user/users/show.html.haml
%section.profile_view
  .container-fluid.mt-2
    .row.profile-sec.py-4.d-flex.justify-content-center.align-items-center.position-relative
      .talenVerseOuter.d-flex.p-4
        .position-relative
          %img.tVerse-img{src: profile_url(current_user)}/
          %img.tVerseCheck-img{src: "/user/img/default/checkImg.png"}/
        .tVerseRigh.flex-1.d-flex.flex-column.align-items-start.ps-4
          .d-flex.w-100.sp-label.justify-content-between
            %span Sport | Diverse
            %span.color-2.fw-bold.spNum-label
              = "##{current_user.id}"
          .text-start.heading-3.mb-4.color-2
            = current_user.name
          .text-start.d-flex.mb-2.mt-2
            %img.tInnerImg.me-2{src: "/user/img/default/vector1.png"}/
            .tText
              = current_user.wallet_address
          .d-flex.w-100.justify-content-between
            %span.tJoinText
              = "Joined | #{current_user.created_at.strftime('%B %Y')}"
      .setShare.d-flex.border.position-absolute
        %img.crs-pointer.setShareicon.border-end.pe-2{alt: "", src: "/user/img/default/setting.png"}/
        %img.crs-pointer.setShareicon.ps-2{alt: "", src: "/user/img/default/share.png"}/
%section.tsContainer.bt-4
  .d-flex.h-100.position-relative.tsContainer-inner
    .leftSection.flex-1.border-end
      .tsmenu-items.menu-items.d-flex.justify-content-between.align-items-center.py-3
        #tabNav.d-flex.justify-content-center.align-items-center.nav
          .nav-item
            = link_to user_profile_path(page: :collected), class: "menu-item nav-link px-2 px-xl-3 active" do
              %span Collected
          .nav-item
            = link_to user_profile_path(page: :created), class: "menu-item nav-link px-2 px-xl-3" do
              %span Created
          .nav-item
            %a.menu-item.nav-link.px-2.px-xl-3{href: "#Favorited"}
              %span Favorited
          .nav-item
            %a.menu-item.nav-link.px-2.px-xl-3.me-3.me-xl-5{href: "#Hidden"}
              %span Hidden
        .d-flex.justify-content-center.align-items-center
          %a.menu-item.px-2.px-xl-3{href: "#link-2"}
            %span Activity
          %a.menu-item.px-2.px-xl-3{href: "#link-3"}
            %span Offers
          = link_to user_profile_path(page: :listings), class: 'menu-item px-2 px-xl-3' do
            %span Listings
          %a.menu-item.ps-2.ps-xl-3
            %img.closeBtn.tInnerImg.me-2{src: "/user/img/default/closeBtn.png"}/
      #tab-content
        .tab-container
          .leftMainContainer.d-flex.flex-wrap.mt-2.moreBox.ps-2.pb-3
            - if params[:page] == 'listings'
              = render partial: 'listing_offers'
            - else
              = render partial: 'collected_offers'

        .tab-container
    .rightSection.position-relative.h-100.py-3
      .d-flex.justify-content-between.align-items-center.position-relative.mb-4.px-3
        .showFilter.filterDiv.position-absolute
          %img.crs-pointer.showMoreBox{alt: "", src: "/user/img/default/filter.png"}/
        .filterHead Filter
        .filterIcn.d-flex.border
          %img.crs-pointer.flitericon.border-end.pe-2.showMoreBox{alt: "", src: "/user/img/default/Small-Icon.svg"}/
          %img.crs-pointer.flitericon.ps-2.showLessBox{alt: "", src: "/user/img/default/Big-Icon.svg"}/
      .py-2.filterSelectOuter
        .my-3.px-4
          .filterselectOuter
            %select.form-select.select-filed{"aria-label" => "Default select example"}
              %option{selected: "selected"} Most Recent
              %option{value: "1"} One
              %option{value: "2"} Two
              %option{value: "3"} Three
        .my-3.px-4
          .filterselectOuter
            %select.form-select.select-filed{"aria-label" => "Default select example"}
              %option{selected: "selected"} Status
              %option{value: "1"} One
              %option{value: "2"} Two
              %option{value: "3"} Three
        .my-3.px-4
          .filterselectOuter
            %select.form-select.select-filed{"aria-label" => "Default select example"}
              %option{selected: "selected"} Chains
              %option{value: "1"} One
              %option{value: "2"} Two
              %option{value: "3"} Three
      .filterPrice.pt-4.pb-2.px-4.px-lg-5.px-xl-5
        .fPrice Price
        .d-flex.align-items-center.justify-content-even
          .text-center
            %div Min
            .price-grp.d-flex.justify-content-start.align-items-center
              %input.input-field.w-100{id: "", placeholder: "", type: "number"}/
          .mx-3.mt-4.priceTo to
          .text-center
            %div Max
            .price-grp.d-flex.justify-content-start.align-items-center
              %input.input-field.w-100{id: "", placeholder: "", type: "number"}/

:javascript

  $(document).ready(function() {
    getAccount(false);
  });