config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users

  root to: 'home#home'

  namespace :admin do
    resources :users
    resources :posts
    resources :categories
  end

  namespace :user do
    resources :nft_posts do
      collection do
        get :explore
        get :mobile_nft
      end
    end
    resources :offers do
      collection do
        get :explore
      end
    end
    resources :bids
    resources :users, only: [:edit, :update]
    get :profile, to: 'users#show'
  end
  resources :users, only: [:update]
  resources :nfts, only: [:show]

  get "/home/*page" => "home#show"

  # API routes
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_for :users,
                  controllers: {
                    sessions: 'api/v1/sessions',
                    registrations: 'api/v1/registrations',
                    passwords: 'api/v1/passwords'
                  },
                  path_names: {
                    sign_in: :login,
                    sign_out: :logout,
                    registration: :signup,
                    password: :forgot_password
                  }

      devise_scope :user do
        post 'users/verify_otp', to: 'registrations#verify_otp'
        post 'users/send_otp', to: 'registrations#send_otp'
        post 'users/resend_otp', to: 'registrations#resend_otp'
      end

      resources :users, only: [:show, :update] do
        member do
          get :profile, to: 'users#show'
          patch :update_profile, to: 'users#update'
          post :follow
          post :unfollow
          get :followers
          get :following
          get :details
          get :posts
        end
      end

      resources :posts do
        collection do
          post :delete
        end
        resources :comments
      end
      resources :roles, only: :index
      resources :feeds, only: :index
      resources :nft_posts, only: [:index, :show]
      resources :nfts, only: [] do
        collection do
          post :sign_nft
          post :sign_royalty
        end
      end
      resources :likes, only: [] do
        collection do
          post :like
          post :dislike
        end
      end
    end
  end
end

app/views/admin/shared/_footer.html.haml
%footer.main-footer
  .pull-right.d-none.d-sm-inline-block
    %ul.nav.nav-primary.nav-dotted.nav-dot-separated.justify-content-center.justify-content-md-end
      %li.nav-item
        %a.nav-link{href: "javascript:void(0)"} FAQ
      %li.nav-item
        %a.nav-link{href: "https://themeforest.net/item/crypto-admin-responsive-bootstrap-4-admin-html-templates/21604673", target: "_blank"} Purchase Now
  © 2022
  = succeed "." do
    %a{href: "https://www.multipurposethemes.com/"} Multipurpose Themes

app/views/admin/shared/_header.html.haml
%header.main-header
  .d-flex.align-items-center.logo-box.justify-content-start
    / Logo
    %a.logo{href: "index.html"}
      / logo
      .logo-mini.w-30
        %span.light-logo
          %img{alt: "logo", src: "/admin/images/logo-letter.png"}/
        %span.dark-logo
          %img{alt: "logo", src: "/admin/images/logo-letter.png"}/
      .logo-lg
        %span.light-logo
          %img{alt: "logo", src: "/admin/images/logo-dark-text.png"}/
        %span.dark-logo
          %img{alt: "logo", src: "/admin/images/logo-light-text.png"}/
  / Header Navbar
  %nav.navbar.navbar-static-top
    / Sidebar toggle button
    .app-menu
      %ul.header-megamenu.nav
        %li.btn-group.nav-item
          %a.waves-effect.waves-light.nav-link.push-btn.btn-primary-light{"data-toggle" => "push-menu", href: "#", role: "button"}
            %i{"data-feather" => "align-left"}
        %li.btn-group.nav-item.d-none.d-xl-inline-block
          %a.waves-effect.waves-light.nav-link.svg-bt-icon.btn-primary-light{href: "contact_app_chat.html", title: "Chat"}
            %i{"data-feather" => "message-circle"}
        %li.btn-group.nav-item.d-none.d-xl-inline-block
          %a.waves-effect.waves-light.nav-link.svg-bt-icon.btn-primary-light{href: "mailbox.html", title: "Mailbox"}
            %i{"data-feather" => "at-sign"}
        %li.btn-group.nav-item.d-none.d-xl-inline-block
          %a.waves-effect.waves-light.nav-link.svg-bt-icon.btn-primary-light{href: "extra_taskboard.html", title: "Taskboard"}
            %i{"data-feather" => "clipboard"}
    .navbar-custom-menu.r-side
      %ul.nav.navbar-nav
        %li.btn-group.d-lg-inline-flex.d-none
          .app-menu
            .search-bx.mx-5
              %form
                .input-group
                  %input.form-control{"aria-describedby" => "button-addon2", "aria-label" => "Search", placeholder: "Search", type: "search"}/
                  .input-group-append
                    %button#button-addon3.btn{type: "submit"}
                      %i{"data-feather" => "search"}
        %li.btn-group.nav-item.d-lg-inline-flex.d-none
          %a.waves-effect.waves-light.nav-link.full-screen.btn-primary-light{"data-provide" => "fullscreen", href: "#", title: "Full Screen"}
            %i{"data-feather" => "maximize"}
        / Notifications
        %li.dropdown.notifications-menu
          %a.waves-effect.waves-light.dropdown-toggle.btn-primary-light{"data-bs-toggle" => "dropdown", href: "#", title: "Notifications"}
            %i{"data-feather" => "bell"}
          %ul.dropdown-menu.animated.bounceIn
            %li.header
              .p-20
                .flexbox
                  %div
                    %h4.mb-0.mt-0 Notifications
                  %div
                    %a.text-danger{href: "#"} Clear All
            %li
              / inner menu: contains the actual data
              %ul.menu.sm-scrol
                %li
                  %a{href: "#"}
                    %i.fa.fa-users.text-info
                    Curabitur id eros quis nunc suscipit blandit.
                %li
                  %a{href: "#"}
                    %i.fa.fa-warning.text-warning
                    Duis malesuada justo eu sapien elementum, in semper diam posuere.
                %li
                  %a{href: "#"}
                    %i.fa.fa-users.text-danger
                    Donec at nisi sit amet tortor commodo porttitor pretium a erat.
                %li
                  %a{href: "#"}
                    %i.fa.fa-shopping-cart.text-success
                    In gravida mauris et nisi
                %li
                  %a{href: "#"}
                    %i.fa.fa-user.text-danger
                    Praesent eu lacus in libero dictum fermentum.
                %li
                  %a{href: "#"}
                    %i.fa.fa-user.text-primary
                    Nunc fringilla lorem
                %li
                  %a{href: "#"}
                    %i.fa.fa-user.text-success
                    Nullam euismod dolor ut quam interdum, at scelerisque ipsum imperdiet.
            %li.footer
              %a{href: "#"} View all
        / User Account
        %li.dropdown.user.user-menu
          %a.waves-effect.waves-light.dropdown-toggle.btn-primary-light{"data-bs-toggle" => "dropdown", href: "#", title: "User"}
            %i{"data-feather" => "user"}
          %ul.dropdown-menu.animated.flipInX
            %li.user-body
              %a.dropdown-item{href: "#"}
                %i.ti-user.text-muted.me-2
                Profile
              %a.dropdown-item{href: "#"}
                %i.ti-wallet.text-muted.me-2
                My Wallet
              %a.dropdown-item{href: "#"}
                %i.ti-settings.text-muted.me-2
                Settings
              .dropdown-divider
              = link_to destroy_admin_session_path, class: 'dropdown-item', method: :delete, data: { turbo_method: :delete } do
                %i.ti-lock.text-muted.me-2
                Logout Admin
        / Control Sidebar Toggle Button
        %li
          %a.waves-effect.waves-light.btn-primary-light{"data-toggle" => "control-sidebar", href: "#", title: "Setting"}
            %i{"data-feather" => "settings"}

app/views/admin/shared/_messages.html.haml
%div{:align => "center"}
  - flash.each do |key, value|
    %div{:class => "alert alert-#{key}"}
      .col-3
        %button.close{"data-dismiss" => "alert", :type => "button"} x
        %h5{:style => "text-align:center"}= value

app/views/admin/shared/_side_bar.html.haml
%aside.main-sidebar
  / sidebar
  %section.sidebar.position-relative
    .multinav
      .multinav-scroll{style: "height: 100%;"}
        / sidebar menu
        %ul.sidebar-menu{"data-widget" => "tree"}
          %li.treeview
            %a{href: "#"}
              %i{"data-feather" => "monitor"}
              %span Dashboard
              %span.pull-right-container
                %i.fa.fa-angle-right.pull-right
            %ul.treeview-menu
              %li.treeview
                %a{href: "#"}
                  %i.icon-Commit>
                    %span.path1
                    %span.path2
                  Options 1 to 5
                  %span.pull-right-container
                    %i.fa.fa-angle-right.pull-right
                %ul.treeview-menu
                  %li
                    %a{href: "index.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 1
                  %li
                    %a{href: "index2.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 2
                  %li
                    %a{href: "index3.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 3
                  %li
                    %a{href: "index4.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 4
                  %li
                    %a{href: "index5.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 5
              %li.treeview
                %a{href: "#"}
                  %i.icon-Commit>
                    %span.path1
                    %span.path2
                  Options 6 to 10
                  %span.pull-right-container
                    %i.fa.fa-angle-right.pull-right
                %ul.treeview-menu
                  %li
                    %a{href: "index6.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 6
                  %li
                    %a{href: "index7.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 7
                  %li
                    %a{href: "index8.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 8
                  %li
                    %a{href: "index9.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 9
                  %li
                    %a{href: "index10.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 10
              %li.treeview
                %a{href: "#"}
                  %i.icon-Commit>
                    %span.path1
                    %span.path2
                  Options 11 to 15
                  %span.pull-right-container
                    %i.fa.fa-angle-right.pull-right
                %ul.treeview-menu
                  %li
                    %a{href: "index11.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 11
                  %li
                    %a{href: "index12.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 12
                  %li
                    %a{href: "index13.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 13
                  %li
                    %a{href: "index14.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 14
                  %li
                    %a{href: "index15.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 15
              %li.treeview
                %a{href: "#"}
                  %i.icon-Commit>
                    %span.path1
                    %span.path2
                  Options 16 to 20
                  %span.pull-right-container
                    %i.fa.fa-angle-right.pull-right
                %ul.treeview-menu
                  %li
                    %a{href: "index16.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 16
                  %li
                    %a{href: "index17.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 17
                  %li
                    %a{href: "index18.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 18
                  %li
                    %a{href: "index19.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 19
                  %li
                    %a{href: "index20.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 20
              %li.treeview
                %a{href: "#"}
                  %i.icon-Commit>
                    %span.path1
                    %span.path2
                  Options 21 to 25
                  %span.pull-right-container
                    %i.fa.fa-angle-right.pull-right
                %ul.treeview-menu
                  %li
                    %a{href: "index21.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 21
                  %li
                    %a{href: "index22.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 22
                  %li
                    %a{href: "index23.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 23
                  %li
                    %a{href: "index24.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 24
                  %li
                    %a{href: "index25.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 25
              %li.treeview
                %a{href: "#"}
                  %i.icon-Commit>
                    %span.path1
                    %span.path2
                  Options 26 to 30
                  %span.pull-right-container
                    %i.fa.fa-angle-right.pull-right
                %ul.treeview-menu
                  %li
                    %a{href: "index26.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 26
                  %li
                    %a{href: "index27.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 27
                  %li
                    %a{href: "index28.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 28
                  %li
                    %a{href: "index29.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 29
                  %li
                    %a{href: "index30.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 30
              %li.treeview
                %a{href: "#"}
                  %i.icon-Commit>
                    %span.path1
                    %span.path2
                  Options 26 to 30
                  %span.pull-right-container
                    %i.fa.fa-angle-right.pull-right
                %ul.treeview-menu
                  %li
                    %a{href: "index26.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 26
                  %li
                    %a{href: "index27.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 27
                  %li
                    %a{href: "index28.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 28
                  %li
                    %a{href: "index29.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 29
                  %li
                    %a{href: "index30.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 30
              %li.treeview
                %a{href: "#"}
                  %i.icon-Commit>
                    %span.path1
                    %span.path2
                  Options 31 to 35
                  %span.pull-right-container
                    %i.fa.fa-angle-right.pull-right
                %ul.treeview-menu
                  %li
                    %a{href: "index31.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 31
                  %li
                    %a{href: "index32.html"}
                      %i.icon-Commit>
                        %span.path1
                        %span.path2
                      Dash 32
          %li.treeview
            %a{href: "#"}
              %i{"data-feather" => "users"}
              %span Members
              %span.pull-right-container
                %i.fa.fa-angle-right.pull-right
            %ul.treeview-menu
              %li
                = link_to admin_users_path do
                  %i.icon-Commit>
                    %span.path1
                    %span.path2
                  Members List
          %li.treeview
            %a{href: "#"}
              %i{"data-feather" => "users"}
              %span Posts
              %span.pull-right-container
                %i.fa.fa-angle-right.pull-right
            %ul.treeview-menu
              %li
                = link_to admin_posts_path do
                  %i.icon-Commit>
                    %span.path1
                    %span.path2
                  Posts List
        .sidebar-widgets
          .mx-25.mb-30.p-30.text-center.bg-primary-light.rounded5
            %img{alt: "", src: "/admin/images/trophy.png"}/
            %h4.my-3.fw-500.text-uppercase.text-primary Start Trading
            %span.fs-12.d-block.mb-3.text-black-50 Offering discounts for better online a store can loyalty weapon into driving
            %button.waves-effect.waves-light.btn.btn-sm.btn-primary.mb-5{type: "button"} Invest Now
          .copyright.text-center.m-25
            %p
              %strong.d-block Talents Admin Dashboard
              © 2022 All Rights Reserved